# Use official OpenJDK 21 image
FROM eclipse-temurin:21-jdk

# Set working directory
WORKDIR /app

# Copy everything
COPY . .

# Build the application
RUN ./mvnw clean install

# Run the application
CMD ["java", "-jar", "target/InventoryManagementSystem-0.0.1-SNAPSHOT.jar"]
